### ISSUE TITLE
Payment prompt

### ISSUE THREAD

**Issue by kattn** [dotkom/Nibble2#45]
It would be nice to have a payment promt to pop up when you add _cash_ to your card reminding you to actually put that amount into the "Rød skrinet".

**Comment by sklirg** [comment]
Hi, and thanks for reporting this problem.

We already have this when you open up the "add money" prompt. See attached image. It reads: "Legg kontanter i pengekassa som står i kjøleskapet, så registrer samme beløp her." I think that's pretty clear, and see no reason to add another prompt afterwards to remind the user to actually put money in the box. 

Additionally, the instructions are to put money in the box _first_ and then update your profile afterwards. Adding a reminder popup _after_ you've updated to remember to put money in the box is counter-intuitive if you're supposed to have put the money in the box first.

We'll reword the prompt slightly to make it more clear that this is for *cash* and not card payments, but we won't add a popup to confirm that you've put money in the box.


![img_20170604_173504](https://cloud.githubusercontent.com/assets/5422571/26763126/ae959c04-494d-11e7-9b4e-f1533fb55b27.jpg)
