### ISSUE TITLE
Account balance in flux during checkout

### ISSUE THREAD

**Issue by sardred** [dotkom/Nibble2#47]
At the moment one checks out their cart, the account balance for the given user seems to be reduced twice for the purchase, before correcting itself. I believe I've also seen the balance go to something far lower than one would expect (going from 40, to -199, to 32 for example)

**Comment by Aborysa** [comment]
The code responsible for updating the user saldo should be: https://github.com/dotkom/Nibble2/blob/master/app/src/services/order/order.service.js#L11-L28
and I can't really see anything obviously wrong with it.
