### ISSUE TITLE
Cash input/output is atrocious

### ISSUE THREAD

**Issue by sardred** [dotkom/Nibble2#50]
We use the add and subtract buttons for cash because the virtual keyboard is somehow worse. The cleanest fix right now seems to be getting a different keyboard, perhaps by going back to Windows.
The reasoning behind why the current method is bad goes as follows: we're already talking about adding and subtracting money to the account, and overlaying addition and subtraction _to the addition and subtraction_ seems to get people a bit confused. 
As for a redesign, look back to the old design perhaps. Buttons for commonly used preset amounts (50, 100, 200, 500) is worth keeping around. There was a suggestion to have basically those as stacking buttons, and a potential clear/reset button instead of buttons for subtraction.

**Comment by FredrikAugust** [comment]
If you're thinking about the "Increment/Decrement Saldo" feature (with the +1, -1, +5, -5, etc. interface), this has been addressed in #62.

**Comment by Aborysa** [comment]
Closing as the shop will not support direct cash withdrawal and deposit in the future.
